#!/bin/bash

set -euo pipefail -o posix

function die() {
    cat - >&2
    exit 1
}

usage=$(cat <<EOF
Usage: gitm <command> [<args>]
EOF
)

function parse() {
    args=()

    while [[ $# -gt 0 ]]; do
        case "$1" in
            -h|--help) echo "${usage}"; exit 0 ;;
            --) shift; args=("$@"); break ;;
            *) printf "Illigal argument: %s\n%s\n" "$1" "${usage}" | die ;;
        esac
        shift
    done
}

parse "$@"
set -- "${args[@]}"

set -x

exec git "$@"
